name: Netlify

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      # 「./dist」にビルド結果が生成する。好きなビルドに変えましょう。
      - uses: pnpm/action-setup@v2
      #- uses: actions/setup-node@v1
      #  with:
        # node-version: 12.x
      #- run: npm ci
      #- run: npm run build
      - run: pnpm i
      - run: pnpm run build

      # Netlifyにデプロイする。「--dir=./dist」の部分はビルド結果ができあがるディレクトリ名に変えましょう。
      - run: pnpm netlify-cli deploy --dir=./.next
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}